version: '3.8'
services:
  db-stats:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  db-main:
    image: postgres:13.7-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  main-server:
    build: ./main-server
    ports:
      - "8080:8080"
    depends_on:
      - db-main
      - stats-server
    environment:
      - SERVER_PORT=8080
      - STATS-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/ewm_main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-server:
    build: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stats:5432/ewm_stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - SERVER-PORT=9090